var ruta = window.location;
var win = window;
var doc = document;
var nav = navigator;
var csl = console;
alert("Haz entrado a " + ruta + ".");
console.log("Mensaje");
console.log(win);
console.log(doc);
console.log(nav);
console.log(csl);
